### ISSUE TITLE
Groups aren't resolved in chat response

### ISSUE THREAD

**Issue by deB4SH** [aziznatour/discord-translator#1]
If you mention a group it isn't correct resolved. See attached images.

![issue_regex_in](https://user-images.githubusercontent.com/5542725/34165756-6f538552-e4dd-11e7-9b3b-70084162bbdd.PNG)

![issue_regex_out](https://user-images.githubusercontent.com/5542725/34165757-6f6bb8a2-e4dd-11e7-8f2a-98e8870bbabf.PNG)

**Comment by aziznatour** [comment]
Fixed in https://github.com/aziznatour/discord-translator/commit/443e7860d04361dfdf4406d1dd4ef0da4a70a5b4
